spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/jobmatch}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
